import { WorkspaceSnapshot } from "@/lib/types";

export const demoSnapshot: WorkspaceSnapshot = {
  categories: [
    { id: "cat-salary", name: "Salary", kind: "income", color: "#007700" },
    { id: "cat-freelance", name: "Freelance", kind: "income", color: "#006699" },
    { id: "cat-groceries", name: "Groceries", kind: "expense", color: "#a55d00" },
    { id: "cat-rent", name: "Rent", kind: "expense", color: "#7b0000" },
    { id: "cat-leisure", name: "Leisure", kind: "expense", color: "#000080" },
    { id: "cat-transport", name: "Transport", kind: "expense", color: "#4c4c4c" },
    { id: "cat-savings", name: "Savings", kind: "savings", color: "#007700" },
  ],
  transactions: [
    {
      id: "txn-1",
      description: "Monthly salary",
      amount: 3200,
      date: "2026-04-01",
      categoryId: "cat-salary",
      tags: ["payday"],
    },
    {
      id: "txn-2",
      description: "Flat rent",
      amount: 1050,
      date: "2026-04-02",
      categoryId: "cat-rent",
    },
    {
      id: "txn-3",
      description: "Groceries",
      amount: 112,
      date: "2026-04-10",
      categoryId: "cat-groceries",
      tags: ["food"],
    },
    {
      id: "txn-4",
      description: "Coffee and lunch",
      amount: 18,
      date: "2026-04-11",
      categoryId: "cat-leisure",
    },
    {
      id: "txn-5",
      description: "Rail card top-up",
      amount: 42,
      date: "2026-04-13",
      categoryId: "cat-transport",
    },
    {
      id: "txn-6",
      description: "Transfer to savings",
      amount: 400,
      date: "2026-04-15",
      categoryId: "cat-savings",
    },
  ],
  budgets: [
    { id: "bud-1", categoryId: "cat-groceries", month: "2026-04", amount: 350 },
    { id: "bud-2", categoryId: "cat-leisure", month: "2026-04", amount: 220 },
    { id: "bud-3", categoryId: "cat-transport", month: "2026-04", amount: 120 },
  ],
  savingsGoals: [
    { id: "goal-1", name: "Emergency fund", targetAmount: 5000, currentAmount: 2400 },
    { id: "goal-2", name: "Japan trip", targetAmount: 3000, currentAmount: 950, targetDate: "2026-11-01" },
  ],
  wishlist: [
    { id: "wish-1", name: "Mirrorless camera", estimatedCost: 1200, priority: 1 },
    { id: "wish-2", name: "Standing desk", estimatedCost: 450, priority: 2, linkedGoalId: "goal-1" },
  ],
  recurring: [
    {
      id: "rec-1",
      name: "Spotify",
      amount: 11,
      categoryId: "cat-leisure",
      billingCycle: "monthly",
      nextRunDate: "2026-04-28",
      providerName: "Spotify",
      isSubscription: true,
    },
    {
      id: "rec-2",
      name: "Netflix",
      amount: 16,
      categoryId: "cat-leisure",
      billingCycle: "monthly",
      nextRunDate: "2026-05-03",
      providerName: "Netflix",
      isSubscription: true,
      trialEndDate: "2026-05-01",
    },
    {
      id: "rec-3",
      name: "Adobe Creative Cloud",
      amount: 52,
      categoryId: "cat-leisure",
      billingCycle: "monthly",
      nextRunDate: "2026-04-30",
      providerName: "Adobe",
      isSubscription: true,
      isPaused: true,
    },
  ],
  allocationRules: [
    { id: "alloc-1", name: "Needs", percentage: 50, categoryIds: ["cat-rent", "cat-groceries", "cat-transport"] },
    { id: "alloc-2", name: "Wants", percentage: 30, categoryIds: ["cat-leisure"] },
    { id: "alloc-3", name: "Savings", percentage: 20, categoryIds: ["cat-savings"] },
  ],
};
